dir:
  external: "./data/external/"
  interim: "./data/interim/"
  processed: "./data/processed/"
  raw: "./data/raw/"
  models: "./models/"

path:
  train: "./data/raw/train.csv"
  test: "./data/raw/test.csv"
  submission: "./data/raw/sample_submission.csv"
  soft_label: "./data/processed/soft_label.npy"

training:
  evaluation_strategy: "epoch"
  per_device_train_batch_size: 16
  per_device_eval_batch_size: 16
  learning_rate: 3e-5
  num_train_epochs: 100
  save_strategy: "epoch"
  save_steps: 1e6
  save_total_limit: 1
  seed: 42
  data_seed: 42
  fp16: True
  remove_unused_columns: False
  load_best_model_at_end: True
  metric_for_best_model: "f1_score"
  label_smoothing_factor: 0.2
  report_to: "none"

trainer:
  early_stopping_patience: 3
